### PR TITLE
Make original author copyright explicit in LICENSE notice.

### PR DESCRIPTION
**Pull request by jvelo**
The original author of the work did not explicitly waived his copyright, so the NOTICE file is misleading in that regard.
This commit adds a copyright mention in the previously mentioned file.

### CODE REVIEW

**Comment by Exagone313** [comment]
I think the original copyright notice should be below the new one.

**Comment by jvelo** [comment]
@Exagone313 that would be ordered by contribution date ? If you have a link that explain how this work, I'm curious.
In the mean time can switch the lines and add the date explicitly.

**Comment by Exagone313** [comment]
I make the assumption that if you add a line in between, you modified the licence.

Thanks for adding the years, too.

You may edit your two commits to have:
* one adding original copyright notice
* one adding years

**Comment by pli01** [comment]
Fixes in 1.1.1

**Pull request closed without merging**
